import numpy as np
A= np.array([[1,2],[3,4]])
print("orginal matrix")
print(A)
print("transpose matrix")
print(A.T)
print("using np.transpose():",np.transpose(A))
det=np.linalg.det(A)
print("determinant:")
print(det)
inv=np.linalg.inv(A)
print("inv:")
print(inv)
B=np.arange(1,13)
print("original array of B:")
print(B)
reshaped=B.reshape(3,4)
print("reshaped:")
print(reshaped)